name = "Steve & Soundless' tech modpack"
author = "Steveplays28, Soundless"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9089dfdb9025ce0d6f1e810775918f52c1bb0ce02d9e0803ca292777ac242fef"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
