name = "Steve & Soundless' tech modpack"
author = "Steveplays28, Soundless"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b663311c2c514f2cd907b15bacfac94264637c28927e82a011a7be9e96b04b63"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
