name = "Steve & Soundless' tech modpack"
author = "Steveplays28, Soundless"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04b80d67e4df2c5c5c2933399e65ea0c5aecdc43b9f7d07fd44192a161a1bd5c"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
