name = "Test modpack"
author = "Steveplays28, Soundless"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33f4b72ce7d6585bd2eb4989dcc8af01741cac8f6ca99241360b289fe5d3a526"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.1"

[options]
acceptable-game-versions = ["1.18, 1.18.2"]
