name = "Steve & Soundless' tech modpack"
author = "Steveplays28, Soundless"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45431aca9ffd3e58953553c87a88d107524411bab4a049b5b45411337bf8da3b"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
